### ISSUE TITLE
Whitespace-insertion missing for structured data that spans multiple block elements

### ISSUE THREAD

**Issue by christianhujer** [RDFLib/pyrdfa3#15]
```
Scenario: Whitespace-insertion missing for structured data that spans multiple block elements
  Given a simple (X)HTML5 document with structured data that spans multiple block elements without whitespace in between like this:
    """
      <!DOCTYPE html>
      <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" vocab="http://schema.org/">
      <head><title>Structured Data Example</title></head>
      <body typeof="BlogPosting">
      <main property="articleBody">
      <p>Foo</p><p>Bar</p>
      </main>
      </body>
      </html>
    """
  When extracting the structured data of articleBody
  Then the structured data should be: "Foo Bar"
```
The actual structured data currently is "FooBar" (space missing).

Although I haven't yet tried to trace it down to the spec, I understand that this might actually be a problem with the RDFa (and microdata, which I expect to have the same behavior) specification, as RDFa itself cannot tell the difference between inline elements and block elements. So I do not know whether this actually should be fixed. However, when the parser knows that it's HTML5+RDFa or XHTML+RDFa, the parser knows what elements are block and what elements are inline. I think it's actually a safer behavior (although I don't know whether that would be spec compliant) to insert a space between elements always, assuming that normally words are not broken by elements, and make an exception for those few elements known to break words, like all inline elements.

The glitch consequence from this issue is that minimized documents don't work unless they insert a single space between block-level elements in order to have words in different elements to not be joined.

**Comment by iherman** [comment]
Could you provide with a small HTML file? I am not sure I 100% understand

Ivan

**Comment by christianhujer** [comment]
Hi Ivan, the following file should do:
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" vocab="http://schema.org/">
<head><title>Structured Data Example</title></head>
<body typeof="BlogPosting">
<main property="articleBody">
<p>Foo</p><p>Bar</p>
</main>
</body>
</html>
```
The key is that `<p>Foo</p><p>Bar</p>` is in the same line without whitespace. In (X)HTML, this is identical with `<p>Foo</p>` being in one line and `<p>Bar</p>` being in the next line. The whitespace between two `<p/>` elements is ignorable.
However, for pyrdfa3 (and all other tools that I have tested so far), this makes a difference. If `<p>Foo</p><p>Bar</p>` are in the same line, the extracted structured data text is "FooBar". If `<p>Foo</p>` and `<p>Bar</p>` are on separate lines, the extracted structure data text is "Foo Bar". If HTML is to be understood properly, the structured data text should be "Foo Bar" in both cases.

**Comment by iherman** [comment]
From the [relevant section of RDFa spec](https://www.w3.org/TR/2015/REC-rdfa-core-20150317/#h-processorconf):

> A conforming RDFa Processor must preserve white space in both plain literals and XML literals. However, it may be the case that the architecture in which a processor operates has made changes to the white space in a document before that document ever reaches the RDFa Processor (e.g., [XMLSCHEMA11-1] processors are permitted to 'normalize' white space in attribute values - see section 3.1.4). 

The behavior you describe is consistent with this: there is no extra space between the two consecutive `p` elements, ie, the fact that the extracted text is `FooBar` is conform to the specification. The HTML5 processor does _not_ add an extra space between two consecutive `p` elements. If you put the paragraphs into separate lines, the HTML5 parser would put a single white space (ie, a space) to replace the new line character, hence you see `Foo Bar`. Similarly, if your code is 

```<p>Foo</p> <p>Bar</p>```

ie, a space between the two paragraphs, the generated term will `Foo Bar` because white space is preserved.

Note that if you use 

```<p>Foo</p>    <p>Bar</p>``` 

(ie, 4 spaces between the paragraphs; this may not show properly on the github comment display), then the generated term will be `Foo    Bar` (ie, 4 spaces in the string), again because white space is preserved. My pyRdfa processor has a non-standard flag to normalize white spaces, in which case the generated term will be `Foo Bar` even in this case. But that is non standard...

**Comment by christianhujer** [comment]
That's all fine. I'm not complaining about multiple whitespace being joined to one, newline being replaced with space and so on.

But what if there is no space between paragraphs, like `<p>Foo</p><p>Bar</p>`? The problem is that in (X)HTML this is two words "Foo" and "Bar", and pyRDFa turns this into one word "FooBar".

Here's more examples:
`<section property="title"><h1>Global Day of CodeRetreat</h1><p>Enjoy a day-long practice event.</p></section>` This comes out as "Global Day of CodeRetreatEnjoy a day-long practive event.". Observe the lack of space between CodeRetreat and Enjoy.

I'm not talking of the preservation of whitespace, but about the insertion of whitespace in order to prevent words from different elements being joined into a single word.

And now that you point it out, from the same section of the RDFa Core 1.1 spec:

> To ensure maximum consistency between processing environments, authors should remove any unnecessary white space in their plain and XML Literal content.

So, if I remove all whitespace that from the perspectives of XML / XHTML / (X)HTML5 is ignorable, I end up with a single line document that has no whitespace between block elements like headlines and paragraphs. And in that case, pyRDFa joins words across paragraphs into single words, and I think that's just wrong.

**Comment by iherman** [comment]
@christianhujer, the important point is to realize that the RDFa processing is defined _after_ parsing, ie, conceptually, on the DOM and not the original source. The detailed processing is defined in [section 7.5](https://www.w3.org/TR/2015/REC-rdfa-core-20150317/#h-s_sequence), which begins by saying:

> Processing would normally begin after the document to be parsed has been completely loaded. 

The rules to generate a literal is in step 11 which says:

> The actual literal is either the value of @content (if present) or a _string created by concatenating the value of all descendant text nodes_, of the current element in turn. 

Ie, what really counts is what text nodes are generated by the parser, because RDFa does _not_ operate, formally, on the original source, it has no information on the fact that the two `p` elements were directly adjacent in the source. And as the HTML5 parser does _not_ add an extra text node into the DOM for the case you describe, the effect you see is the right one indeed.

Raising an issue by the RDFa WG is of course possible, although that group is not operational any more, and it is not clear whether a new incarnation would be created. But, I am afraid, even if the group was active, the response would probably be to raise this issue with the HTML5 WG insofar as the parsing rules for HTML5 should be modified to include an extra text node into the DOM in the case you describe.

Sorry...

**Comment by christianhujer** [comment]
@iherman I think you've just mentioned the problem.
I think it's irrelevant that it happens at the DOM or whether the DOM contains extra text nodes. I think the problem is not the parsing but the join rule. I think from my perspective it should be this:
> The actual literal is either the value of `@content` (if present) or a string created by concatenating the value of all descendant text nodes *with space*, of the current element in turn.
I understand that it cannot be like that in general, as this rule would "fix" the behavior regarding (X)HTML block elements, but it would potentially break (X)HTML inline elements like `<wbr/>` or `<span/>` which do not separate words.

Anyhow, thank you very much for discussing this issue with me and significantly improving my understanding of the RDFa specs. And sorry for wasting your time with what's turned out to be a non-issue, i.e. correct implementation of the spec. I think you can close the issue as "not a bug".
