### ISSUE TITLE
html5lib bug resolved?

### ISSUE THREAD

**Issue by robmyers** [RDFLib/pyrdfa3#23]
Regarding this warning:

    Warning (2013-07-16): the latest version of the html5lib package has a bug. This bug manifests itself if 
    the source HTML file contains non-ASCII Unicode characters Until the bug is handled, users should 
    use the older, 0.95 version. It can be downloaded at 
    https://code.google.com/p/html5lib/downloads/detail?name=html5lib-0.95.tar.gz

I've tried with a recent version of html5lib and it seems to handle Unicode OK. Is there a test case I can use to confirm this?

Thank you.

**Comment by iherman** [comment]
To be very honest... I do not remember any more what the exact problem was. The code itself is much older than 2013 (it was not developed on github, originally, just migrated there), and I have not looked at this ever since.

I am actually confident that the latest release of html5lib should be fine, unless somebody has some other information. If so, I am happy to remove that comment.

**Comment by robmyers** [comment]
That would be great. To reflect this change, setup.py would also need install_requires updating to:

```
install_requires=[
    "rdflib",
    "html5lib",
]
```

I can change this and send a pull request or it might just be quicker if you would be willing to do it.

Thank you!

**Comment by iherman** [comment]
I would appreciate a pull request, to be honest; my days these week are a bit busy...

Thanks!
